extends:
  - plugin:react/recommended
  - standard

plugins:
  - standard
  - promise
  - react

rules:
  no-return-assign: off
  max-len:
    - 2
    - 80
    - 2

  comma-dangle:
    - error
    - only-multiline

  space-before-function-paren:
    - error
    - never
